### ISSUE TITLE
CIS Benchmark Rules

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#107]
https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf

**Comment by kickroot** [comment]
Based on https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf

Add rules to https://github.com/openraven/aws-cis-1.2. We'll make this public closer to release.

**Comment by belosh59** [comment]
Already Done.
