### ISSUE TITLE
Policy Path Collision

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#116]
**Issue:**
The policy acquisition service currently stores repos in the form `~/.magpie/policies/<policy_repo_name>/`.  This opens up collisions when a user has policies with the same policy name on differenct SCMs (Github, Gitlab, etc).

**Solution**
Modify the filesystem path to be of the form `./magpie/policies/<scm domain>/<org>/<repo>`

For example: `./magpie/policies/github.com/openraven/cis-benchmark-1.2`.

**Comment by belosh59** [comment]
Already Done.
