### ISSUE TITLE
CSPM Text Output Format

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#117]
Rather than the raw YAML output, format the default report into a more column-oriented approach containing scan metadata.  A good example to follow is the old SourceClear scanner. Sample output can be found here: https://miro.medium.com/max/4000/0*vxP2YxGFBaG1y8N8.png

Features that would be good to see:
1. Scan date/time/duration
2. Total violations found
3. The policies used in the scan
3. For each violation show: policy name, rule name, rule GUID, resource id (ARN for amazon)
4. One option to reduce column clutter is to break up the report by Policy Name, using the policy name as a title above the list of violations for each.

You may have to truncate policy and rule names to ensure they fit into the columns.

**Comment by kickroot** [comment]
Think human readable report more than a yaml dump.

**Comment by stefansjfw** [comment]
![image](https://user-images.githubusercontent.com/57057282/119835633-4b0dcc00-bf01-11eb-9f67-bd6fbd75100e.png)

@kickroot Does this look good to you ?

**Comment by kickroot** [comment]
Nice work! :+1:

**Comment by belosh59** [comment]
Already Done
