### ISSUE TITLE
Discovery Test System

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#123]
We spoke about the need to have a proper test environment to test both Magpie and the Open Raven product. We spoke about potentially using LocalStack. The challenge is the free version doesn't support many services so not good for the open source community and the paid version doesnt support all services we discover and want top test anyways. There was a discussion about potentially using Boto3 and essentially syncing the API's and providing a mock to the API ie a free open source version of LocalStack that is complete.

┆Issue is synchronized with this [Jira Task](https://openraven.atlassian.net/browse/RAD-217) by [Unito](https://www.unito.io)

**Comment by curphey** [comment]
Create a local stack test env that we can use to test discovery and scanning. The open source version of Local Stack https://github.com/localstack only supports a very limited set of services. We can pay for the commercial for testing but it still doesn't cover that many given their license we still cant make that available to all users. A better option would be to build a free and open source version, kinda like cloud goat that would enable anyone to spin up a mock AWS with whatever configuration they want. Would be great for testing tools and for teaching people cloud security.
