### ISSUE TITLE
Add a "manualControl" boolean field to policy rules.

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#136]
When a rule cannot (or shouldn't) be verified by Magpie, we need to set a top-level value in it called `manualControl` and set the value to `true`.  This field should default to `false` if missing or explicitly set to `false`.

For any rule with `manualControl` enabled, the `PolicyAnalyzerService` must not attempt to execute SQL or Python code.  Instead log a statement that the rule will not be checked and move on to the next rule.

Set this value on all existing rules that are unable to be verified with Magpie.

**Comment by belosh59** [comment]
Already Done.
