### ISSUE TITLE
Utilize Flyway for Schema Management

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#151]
Use SQL based migrations to create the `asset` table in Postgres.  https://flywaydb.org/documentation/concepts/migrations#sql-based-migrations

We currently autogenerate tables dynamically based on the resource type.  You'll need to re-create the existing columns, but be aware some have changed based on names from the members of https://github.com/openraven/magpie-api/blob/magpie_resource/src/main/java/io/openraven/magpie/api/MagpieResource.java

Migrations should happen when magpie-discovery is run.

**Comment by PrzemyslawTusinski** [comment]
@kickroot @belosh59 
Does this task involves changning the upserting from AWSResource to MagpieResource in persistance?

**Comment by kickroot** [comment]
Yeah, let's make it include all required changes to upsert into PG.

**Comment by belosh59** [comment]
Already done
