### ISSUE TITLE
Rule Normalization and Refactoring

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#153]
As described here: https://github.com/openraven/magpie/wiki/Proposal-for-changes-to-policies-and-rules.  It's probably best to create the new repo (cspm-kb) and move rules and policies into this as they are refactored.

**Comment by kickroot** [comment]
@stefansjfw  https://github.com/openraven/cspm-kb is ready to go!

**Comment by belosh59** [comment]
Already done.
