### ISSUE TITLE
Update failing Integration Tests

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#198]
It looks like the addition of AWS Backup calls within certain resources has caused IT's to fail on the `backup-discovery` branch: https://github.com/openraven/magpie/runs/3254454269?check_suite_focus=true

**Comment by belosh59** [comment]
https://github.com/localstack/localstack

BackUop service is under the Pro version.
We doesn't have it defined even in LocalStackContainer Enum
```
public enum Service implements EnabledService {
        API_GATEWAY("apigateway", 4567),
        EC2("ec2", 4597),
        KINESIS("kinesis", 4568),
        DYNAMODB("dynamodb", 4569),
        DYNAMODB_STREAMS("dynamodbstreams", 4570),
        // TODO: Clarify usage for ELASTICSEARCH and ELASTICSEARCH_SERVICE
//        ELASTICSEARCH("es",           4571),
        S3("s3", 4572),
        FIREHOSE("firehose", 4573),
        LAMBDA("lambda", 4574),
        SNS("sns", 4575),
        SQS("sqs", 4576),
        REDSHIFT("redshift", 4577),
        //        ELASTICSEARCH_SERVICE("",   4578),
        SES("ses", 4579),
        ROUTE53("route53", 4580),
        CLOUDFORMATION("cloudformation", 4581),
        CLOUDWATCH("cloudwatch", 4582),
        SSM("ssm", 4583),
        SECRETSMANAGER("secretsmanager", 4584),
        STEPFUNCTIONS("stepfunctions", 4585),
        CLOUDWATCHLOGS("logs", 4586),
        STS("sts", 4592),
        IAM("iam", 4593),
        KMS("kms", 4599);
```

Checking if we could mock it somehow

**Comment by belosh59** [comment]
So from what I see you already trying to use kind of ServiceLocator approach within the BackupUtills class, by returning already defined clients, and instantiate them on a flight.

So far we have a problem that not all of clients are allowed under the free version of LocalStack. 
I dont see any reason to buy localstack just for satisfy our integration testing, coz we already faced with several discrepancies between their API and real AWS API.
More controlled and straightforward approach here is to mock the AWSClient and its response for required discovery.
Mocked data could be taken from the existing AWS Env.  

If we will expand Service Locator pattern for clients and dependent objects we will have better ability to test them.

Other alternatives is lightweight IoC:
http://picocontainer.com/
https://github.com/google/guice
