### ISSUE TITLE
JSON and CSV Output

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#201]
We need more than just a text report output in `magpie-policy`.  CSV and JSON outputs are requested.  This will be broken down into two parts:

1) io.openraven.magpie.core.cspm.services.ReportService should be moved into the `magpie-api` project and renamed `PolicyOutputPlugin`.
2) The existing ReportServiceImpl should be renamed `TextPolicyOutputPlugin`.
3) New plugins for CSV and JSON should be created
4) Implement a ServiceLoader as we have done for `magpie-discovery` allowing jar file implementations to be dropped in the classpath and discovered at runtime.
5) Build configuration loading as done with the discovery plugins so users can enable/disable/configure policy output plugins.

**Comment by belosh59** [comment]
With ScanResults we would also need to include  PolicyContext, Violation, IgnoredReason into the magpie-api,
which will change abstract nature of the api package itself

```
public class ScanResults {
  private List<PolicyContext> policies = List.of();
  private Map<PolicyContext, List<Violation>> violations = Map.of();
  private Map<PolicyContext, Map<Rule, IgnoredReason>> ignoredRules = Map.of();
  private int numOfViolations;
```

**Comment by belosh59** [comment]
JSON output example:
[out.txt](https://github.com/openraven/magpie/files/6969621/out.txt)

**Comment by belosh59** [comment]
CSV output result, 
Parsed CSV :  https://docs.google.com/spreadsheets/d/1Abwtr-I9FbNXDfZWVzeaiXJUkFXJocWfO0Ue9R2O3DY/edit?usp=sharing
Plain CSV: https://drive.google.com/file/d/1hrw4ZCHSIo8E4XwaWECqXAtSt62WQGs0/view?usp=sharing

**Comment by kickroot** [comment]
Good work, but I think I should have added a few requirements to the CSV output.  The above examples aren't easily parsable by CSV readers due to the various header sections.  We need a strict column/row format that can be read by other tools.

Think something more like a database table, even if that means duplication of values across the various rows.

**Comment by belosh59** [comment]
@kickroot 
Prepared changes to CSV violations output:
Plain csv:
https://drive.google.com/file/d/1LWkyC7F2Crp8XhgVt_N6dcArxAaIZ4xa/view?usp=sharing
Parsed
https://docs.google.com/spreadsheets/d/1Yx4vbrigxw5Yuf5gyIwRyG_hcxmXYm-_34oqcfbKWnA/edit?usp=sharing

**Comment by kickroot** [comment]
Looks much better! Can we get columns for the ruleId and policyId as well?  It'll help with tool automation downstream from this.

**Comment by belosh59** [comment]
Definitely
