### ISSUE TITLE
GCP CIS Benchmark Security Rules

### ISSUE THREAD

**Issue by curphey** [openraven/magpie#205]
Develop the security rules for GCP. This work has already been started. 

https://github.com/openraven/cspm-kb/blob/main/policies/cis_gcp_foundations_benchmark.yaml

https://www.cisecurity.org/blog/new-cis-benchmark-for-google-cloud-computing-platform/

**Comment by belosh59** [comment]
Intermediate testing for GCP rule 3.6
```
Ensure that there is no rule matching the below criteria:
 SOURCE_RANGES is 0.0.0.0/0
 AND DIRECTION is INGRESS
 AND IPProtocol is tcp or ALL
 AND PORTS is set to 22 or range containing 22 or Null (not set)
```

<img width="872" alt="Screenshot 2021-09-07 at 09 01 47" src="https://user-images.githubusercontent.com/26186899/132292592-f2fefbb3-c118-4b16-95a2-355a15d4a1a1.png">
