### ISSUE TITLE
CLI improvements

### ISSUE THREAD

**Issue by curphey** [openraven/magpie#208]
Note : We can probably break this down into multiple issues

Today you have to clone the repo and do more steps than is needed. Building previous CLI's (SRC:CLR) it was useful to users for all the functionally to be in the CLI.

Initial Run -  Pull the container at first start. 
Update - On each run check its using the latest container and flag for an update with --update and an option to always update for those cron job running it. 
Add accounts  --add-accounts and be able to pass in secret keys and tokens
Help --help shows all the switches and in terminal help. 
Scan  --scan --aws-account 
Output --output takes json,csv, shell etc and defaults to shell
Verbosity --verbosity takes --loud spits all output, --quiet just spits out stages and findings
Evaluation --evaluation takes --discovery-only 

There maybe others. I can look at https://help.veracode.com/r/Install_the_Veracode_SCA_Agent_with_PowerShell

┆Issue is synchronized with this [Jira Task](https://openraven.atlassian.net/browse/RAD-226) by [Unito](https://www.unito.io)

**Comment by curphey** [comment]
I also think this should all be in main repo not a separate quick run repo.

**Comment by kickroot** [comment]
TODO: Break into smaller issues.

**Comment by curphey** [comment]
I think this is becoming more and more important as we move forward
