### ISSUE TITLE
Security Rule for Command and Control Servers

### ISSUE THREAD

**Issue by curphey** [openraven/magpie#218]
Build a rule that parses security groups and determines if there is potential egress / exfiltration to a list of command control services. ngrok https://ngrok.com/ is one example but we should populate with a known list and make sure that list is updatable.

┆Issue is synchronized with this [Jira Task](https://openraven.atlassian.net/browse/RAD-233) by [Unito](https://www.unito.io)

**Comment by curphey** [comment]
I am trying to get a maintained list of C@C servers. In the interim here is one https://exchange.xforce.ibmcloud.com/collection/Botnet-Command-and-Control-Servers-7ac6c4578facafa0de50b72e7bf8f8c4

**Comment by curphey** [comment]
And another http://rules.emergingthreats.net/open/suricata/rules/botcc.rules

**Comment by curphey** [comment]
https://github.com/OISF/suricata has some interesting data worth looking at

**Comment by curphey** [comment]
https://github.com/OISF/suricata-intel-index/blob/master/index.yaml

**Comment by kickroot** [comment]
@curphey what policy will this go under?  It's not CIS or Ransomware related.  It seems like we need a new policy somewhere?

**Comment by curphey** [comment]
It's ransomware. It's an indicator of compromise. Eventually we may want to pull it out into a general IOC one or something but for now ransomware makes most sense.
