### ISSUE TITLE
Remove all traces of sentry.io

### ISSUE THREAD

**Issue by curphey** [openraven/magpie#244]
I noticed we were throwing some errors and see there is still some old crufty Sentry code lying around. 
<img width="727" alt="Screen Shot 2021-08-23 at 8 19 42 PM" src="https://user-images.githubusercontent.com/143776/130550619-7fc10665-ca4d-4367-97cd-3ba731fd6772.png">

**Comment by kickroot** [comment]
This is no old cruft, we specifically added back into Magpie at Mike's request.  You two should discuss and get on the same page.

**Comment by curphey** [comment]
Closed out because this is a feature. If you use sentry then you add your key, if not it simply doesn't run and spits out and error so no privacy issues.
