### ISSUE TITLE
Need a structure to easily map between security standards/compliance to security rules and vice-versa

### ISSUE THREAD

**Issue by the-win** [openraven/magpie#280]
* security standards and security rules are a many-to-many relationship
* security standards are often a list of requirements, with each requirements achieved by security rules.

┆Issue is synchronized with this [Jira Task](https://openraven.atlassian.net/browse/RAD-204) by [Unito](https://www.unito.io)

**Comment by the-win** [comment]
PolicyId: #auto generated unique based on create date
policyName: [Security standard] #displayname of policy
cloudProvider: #selectable list [AWS, GCP, Azure, other]
shortDescription: #1 sentence description
longDescription: #full description
version: #auto-increment
lastUpdated: #automatically generated based on submits
requirements:
  name:req1
    meta1:value1 #meta values should show up in user viewable order
    meta2:value2
    meta3:value3
    rules:
      - # list or rules to implement requirement
      - # any listed rule will be added to check against the policy
      - # a single requirement might have many rules


EXAMPLE
PolicyId: 20211101-c9e120b6-04e5-11ec-9a03-0242ac130003
policyName: "CIS Amazon Web Services Foundations Benchmark v1.3.0"
cloudProvider: "AWS"
shortDescription: "Guidance for configuring security options of foundational, testable, and architecture agnostic settings"
longDescription: >
prescriptive guidance for configuring security options for a subset of Amazon Web Services with an emphasis on foundational, testable, and architecture agnostic settings. Specific Amazon Web Services in scope for this document include:
 AWS Identity and Access Management (IAM)
 AWS Config
 AWS CloudTrail
 AWS CloudWatch
 AWS Simple Notification Service (SNS)
 AWS Simple Storage Service (S3)
 AWS VPC (Default)
To obtain the latest version of this guide, please visit http://benchmarks.cisecurity.org

This benchmark was created using a consensus review process comprised of subject matter experts. Consensus participants provide perspective from a diverse set of backgrounds including consulting, software development, audit and compliance, security research, operations, government, and legal.

version: 1
lastUpdated: 2021-11-01 11:11:11
requirements:
  name:1.1 Maintain current contact details
    category:Identity and Access Management
    description:Ensure contact email and telephone details for AWS accounts are current and map to more than one individual in your organization.
An AWS account supports a number of contact details, and AWS will use these to contact the account owner if activity judged to be in breach of Acceptable Use Policy or indicative of likely security compromise is observed by the AWS Abuse team. Contact details should not be for a single individual, as circumstances may arise where that individual is unavailable. Email contact details should point to a mail alias which forwards email to multiple individuals within the organization; where feasible, phone contact details should point to a PABX hunt group or other call-forwarding system.
    Rationale: If an AWS account is observed to be behaving in a prohibited or suspicious manner, AWS will attempt to contact the account owner by email and phone using the contact details listed. If this is unsuccessful and the account behavior needs urgent mitigation, proactive measures may be taken, including throttling of traffic between the account exhibiting suspicious behavior and the AWS API endpoints and the Internet. This will result in impaired service to and from the account in question, so it is in both the customers' and AWS' best interests that prompt contact can be established. This is best achieved by setting AWS account contact details to point to resources which have multiple individuals as recipients, such as email aliases and PABX hunt groups.
    Audit: |
      This activity can only be performed via the AWS Console, with a user who has permission to read and write Billing information (aws-portal:*Billing )
       1. Sign in to the AWS Management Console and open the Billing and Cost Management console at https://console.aws.amazon.com/billing/home#/.
      2. On the navigation bar, choose your account name, and then choose My Account.
      3. On the Account Settings page, review and verify the current details.
      4. Under Contact Information, review and verify the current details.
  remediation: lorem ipsum
  references: lorem ipsum
    rules:
      - opnrvn-r-xyz

**Comment by curphey** [comment]
I dont think this works. Standards have subsections and we need to know the controls that map to the subsections ie CIS standards 1.1, section 2.1. That subsection needs the description as well as all of that data needs to be extrapolated out to build reports. Maybe this is your requirements and meta fields?

We also moved all remediation guidance to the docs (@WIP)

**Comment by curphey** [comment]
Also to keep this in context this must apply to all the standards in the sheet https://docs.google.com/spreadsheets/d/1N_EgNF5aG2LRKN7LBgVmdb9Xc9gfVfMjomeir-pQ2uI/edit#gid=0

**Comment by the-win** [comment]
I saw the "subsection" as the requirement identified by name i.e. "1.1 maintain current contacts"
I did have a question if we think the "control ID" needs to be separated from the "control name."  and how generically that would apply to policies (security standards and non standards). I think it can easily be explicitly specified, or smartly pulled out by separating numbers from characters, of course that assumes that the control ID is always a number.

I also had the question if CIS standards 1.1 should be defined by the same file as CIS standards 1.2. I went with the the direction that if the CIS standard changes or updates, it should be a different file. Is there a world where a user might need to maintain v1.1 separate from v1.2? Is it better to have a single file with CIS standards, then in it sections of 1.1 and 1.2?

Yes, my intent was for the metafields to be unconstrained for reports, since different standards, or DIY governance policies will likely have different structures. The belief is that all of them will have a list of subsections though i.e. requirements. What wasn't obvious if they all grouped subsections into sections, but since for the standards I looked at, a section never itself holds a requirement, then it could just be another metadata field.

If remediation is in a separate doc, do we need to keep yet a separate mapping? Or is the suggestion that we don't need the full text here, just a id/link?

**Comment by the-win** [comment]
updated format, which works better for Java mapping:

​​PolicyId: #auto generated unique
policyName: [Security standard] #displayname of policy, expected to be human readable
cloudProvider: #selectable list [AWS, GCP, Azure, other]
shortDescription: #1 sentence description
longDescription: #full description
version: #auto-increment
#this is not required in the policy definition (assume 'true')
enabled: false
#this is not required in the policy definition (assume 'true')
archived: false
schedule: 0 0 0 * * *
lastUpdated: #automatically generated based on submits
Section:
 - SectionID: #autogenerated - maybe null IFF there is one section (for back-compat)
   # if section ID is null, the rest of these fields, other than list of rules, are optional
   refid: 1.1
   name: asdfasdf
   description: asdfa sdf asdfasdf asdf asdf
   # these are optional&additional fields/description/etc, mostly for reporting
   meta:
     meta1: value1 #meta values should show up in user viewable order
     meta2: value2 #common metafields are name, category, controlId, name, description, remediation, and references
     metaN: valueN #arbitrary number of meta fields
     remediation: >
       dsfasdf
       asdf
       asdf
       asdfasdf
       asdf
   rules:
     - # list or rules to implement requirement
     - # any listed rule will be added to check against the policy
     - # a single requirement might have many rules
 - SectionID: #autogenerated
     refid: 1.2
     name: sdfsdf
     description: sfsdf asdf asdf asdf asdf
     meta:
       meta1: value1 #meta values should show up in user viewable order
       meta2: value2 #common metafields are name, category, controlId, name, description, remediation, and references
     rules:
       - # list or rules to implement requirement
       - # any listed rule will be added to check against the policy
       - # a single requirement might have many rules
