### ISSUE TITLE
Difficulties while executing the ./magpie.sh

### ISSUE THREAD

**Issue by Mayuresh-Coditas** [openraven/magpie#583]
I went through the Read.me file also followed the docs from here - [https://github.com/openraven/docs/blob/main/docs/Current%20Projects/Magpie/getting-started.md](url)

But I guess it is not sufficient.
Current status - 
1. All maven dependencies have been resolved.
2. mvn clean package install && mvn --projects magpie-cli assembly:single [Successful]
3. Non-shaded magpie-cli.jar is build successfully.
4. Config.yaml is updated

![image](https://github.com/openraven/magpie/assets/82996769/3a5c648a-672d-4111-ab4f-8733d81b0eb2)

Now, I want to execute GCP project & policy output.
Hence, copied those jars to Plugins folder, 
![image](https://github.com/openraven/magpie/assets/82996769/9b66e40c-3a2d-48fe-b410-82dc56185dc3)

But when I try to execute the magpie.sh, it shows the below error messages.
![image](https://github.com/openraven/magpie/assets/82996769/764d357f-9b8b-4974-86f2-01c8ade618a7)
![image](https://github.com/openraven/magpie/assets/82996769/892475c9-db52-47b1-98e3-85d0f5a91027)

**Comment by kickroot** [comment]
Hi Mayuresh,
Based on our call I've made some tweaks to Magpie and verified Windows support.  You can see the changes from the PR: https://github.com/openraven/magpie/pull/584/files

I'd like you to re-attempt to run magpie using the following instructions:

1. `git pull origin main` to ensure you have the latest changes
2. `mvn clean install -DskipTests`
3. `mvn clean package -DskipTests`
4. `cd magpie-cli`
5. `mvn assembly:single -DskipTests`
6. Unzip the Magpie distribution zip
7. From the root of the unzipped folder, run `magpie-discovery.bat` and verify the output

Please do not modify the distribution package (renaming/removing/moving files), just edit config.yaml as needed.  

Thanks!

**Comment by Mayuresh-Coditas** [comment]
Hi @kickroot 
Thanks for the quick response.

 I followed the above process and in the end, while executing the magpie-discovery.bat it returns the below error.
 
![image](https://github.com/openraven/magpie/assets/82996769/3cf7bbcc-08ae-43cd-9a21-4174da2469e3)

**Comment by kickroot** [comment]
That error indicates that the required fat(uber) jars were not built.  Please ensure you ran the 2nd and 3rd commands as shown above and do *not* include the `-P -uberjar` parameters (that section was for building non-uber jars if using Magpie as a library in another application.

I'm happy to hop on another call and walk through it if needed.
