### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#8]
We are in need of a Dockerized version of Magpie.   

- Users need to be able to pass in a config file to the image at runtime
- Environmental variables (likely needed for AWS credential) would be useful
- If the Magpie stdout is piped to a mapped file the user can get results via output json file.

**Comment by medelibero** [comment]
I will work on creating a Dockerized version of Magpie.

**Comment by kickroot** [comment]
Great, once you have the image building I can get it hosted either here on Github or on Dockerhub.
