### ISSUE TITLE
Schema Audit

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#88]
Walk through all asset groups in `openraven/openraven/asset-groups/-/tree/main/src/main/java/io/openraven/assets/assetconfigurations` and verify we are matching all the data paths defined, as this is needed for internal compatibility.

The one exception is in cases where Open Raven doesn't currently follow camelCase. As in:
`static final String ENCRYPTION = "supplementaryConfiguration.ServerSideEncryptionConfiguration.rules";`

This should in fact be `static final String ENCRYPTION = "supplementaryConfiguration.serverSideEncryptionConfiguration.rules";`

Please note the offending data paths and we'll update this internally for consistency.

**Comment by PrzemyslawTusinski** [comment]
This is wrong in both aws-discovery and magpie
In S3
static final String REPLICATED = "supplementaryConfiguration.BucketReplicationConfiguration";

In magpie and aws-discovery we use "supplementaryConfiguration.replicationConfiguration" and "supplementaryConfiguration.ReplicationConfiguration"

**Comment by PrzemyslawTusinski** [comment]
In S3 there as there are couple of not correctly capitalized paths
```
    static final String SIZE = "supplementaryConfiguration.size.BucketSizeBytes";
    static final String NUMBER_OF_OBJECTS = "supplementaryConfiguration.size.NumberOfObjects";
    static final String ENCRYPTION = "supplementaryConfiguration.ServerSideEncryptionConfiguration.rules";
    static final String HOSTED = "supplementaryConfiguration.BucketWebsiteConfiguration";
    static final String REPLICATED = "supplementaryConfiguration.BucketReplicationConfiguration";
    static final String OBJECT_LOCK = "supplementaryConfiguration.BucketObjectLockConfiguration.objectLockEnabledAsString";
```

DynamoDB
`static final String BACKED_UP = "supplementaryConfiguration.ContinuousBackupsDescription.continuousBackupsStatus";`

In Reshift there is
` static final String CREATION_TIME = "resourceCreationTime";`
which should be 
` static final String CREATION_TIME = "createdIso";`
Unless there is something that translates createdIso to resourceCreationTime

All other paths are matching aws-magpie schema

Although in DynamicDB There is 
`static final String MOUNT_INFO = "configuration.mountTargets";`
Which matches both aws-magpie and aws-discovery. It should be 
`static final String MOUNT_INFO = "supplementaryConfiguration.mountTargets";`

**Comment by kickroot** [comment]
Please make all needed changes in Magpie and I'll organize internal work with the Engineering team to update the paths in the product as needed. Thanks!

**Comment by PrzemyslawTusinski** [comment]
Everything is matching in magpie. 
Regarding DynamicDB which have in both discovery and magpie:
`static final String MOUNT_INFO = "configuration.mountTargets";`
And probably should be
`static final String MOUNT_INFO = "supplementaryConfiguration.mountTargets";`

Should I make this change?

**Comment by kickroot** [comment]
@PrzemyslawTusinski yes please, `configuration` is reserved for only the main response builder.

**Comment by PrzemyslawTusinski** [comment]
Everything we use in assests group everything should be good now.
I just figured one thing which is related to using paginators in magpie and not using them in aws-discovery.

In aws-discovery we have
```
getAwsResponse(
                () -> client.listDatabases(ListDatabasesRequest.builder().catalogName(data.resourceName).build()),
                (resp) -> data.supplementaryConfiguration = PayloadUtils.update(
                        data.supplementaryConfiguration, Map.of(keyname, resp)),
                (noresp) -> data.supplementaryConfiguration = PayloadUtils.update(
                        data.supplementaryConfiguration, Map.of(keyname, noresp))
        );
```
Which saves ListDatabasesResponse
```
getAwsResponse(
      () -> client.listDatabasesPaginator(ListDatabasesRequest.builder().catalogName(resource.catalogName()).build())
        .stream()
        .map(ListDatabasesResponse::toBuilder)
        .collect(Collectors.toList()),
      (resp) -> AWSUtils.update(data.supplementaryConfiguration, Map.of(keyname, resp)),
      (noresp) -> AWSUtils.update(data.supplementaryConfiguration, Map.of(keyname, noresp))
    );
```
Which saves List<ListDatabasesResponse>
Thouse are not matching.
What we could do is instead of saving whole response just save interesting resource which is I beleve always just one member here it would be 

`client.listDatabases(ListDatabasesRequest.builder().catalogName(data.resourceName).build()).databaseList(),`
Instead of 
`client.listDatabasesPaginator(ListDatabasesRequest.builder().catalogName(resource.catalogName()).build()).`

It would require some changes in both magpie and aws-discovery

**Comment by kickroot** [comment]
@PrzemyslawTusinski this is completed, correct?

**Comment by PrzemyslawTusinski** [comment]
@kickroot  Yes this is completed
