### ISSUE TITLE
Persistence Plugin (magpie-persist)

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#90]
### Persist discovered assets into PostgreSQL.  

- Add a new Maven sub-module to magpie-parent called `magpie-persist`
- Receive messages off the incoming queue
- Insert one row per received message 
- This module does not need to perform read operations on existing tables (no need for select queries)
- Overwrite previously written data (see Primary Keys for details)

#### Primary Keys
Primary keys must be a String value that is derived from a resource's `arn`.  We'll use a deterministic formula to convert arns to keys:
```
/**
 * Inspired by https://github.com/elastic/elasticsearch/blob/c610ef2955d2d147503968434879dfaf6aa24177/server/src/main/java/org/elasticsearch/common/TimeBasedUUIDGenerator.java
 */
public class EncodedNamedUUIDGenerator {

  public static String getEncodedNamedUUID(String target) {
    if (target.isEmpty()) {
      throw new IllegalStateException("Target for Encoded Named UUID is empty.");
    }

    byte[] targetBytes = target.toLowerCase().getBytes();
    UUID uuid = UUID.nameUUIDFromBytes(targetBytes);

    ByteBuffer uuidBytes = ByteBuffer.wrap(new byte[16]);
    uuidBytes.putLong(uuid.getMostSignificantBits());
    uuidBytes.putLong(uuid.getLeastSignificantBits());

    return Base64.getUrlEncoder().withoutPadding().encodeToString(uuidBytes.array());
  }

}
```
This technique will give us a single row per resource, updates should overwrite previous versions for a given resource.

#### Dynamic Tables
Use one table per resource type.  Tables will all have the same schema format and have a name based on the resource type they hold. For example:
`"AWS::Batch::ComputeEnvironment"` becomes `AWSBathComputeEnvironment`.  Keep the capitalization but remove all colons.

You'll need to figure out  how to determine when to create tables. The goal is for this plugin to dynamically create tables when new resources arrive. This allows us to accommodate non-AWS resources when they are discovered (we'll have to adjust later for the ARN field).

#### Schema Management
Determine the best way to handle creating tables and their associated schema.  I'd prefer the use of a ready-made schema management tool (maybe Liquibase or Flyway?).  One that can function as a Java library will most likely be required as you create tables dynamically.

#### Configuration
All required DB credentials (username, password, url, schema, etc) should be loaded via a plugin config similar to the AWS Plugin.

#### Schema
You'll want to match the schema currently in development internally. See the #bye-es branch of AWS Discovery (/aws-discovery/-/blob/bye-es/data/src/main/java/io/openraven/data/interfaces/AWSResource.java)

Favor JDBI over a full-featured ORM unless you have a specific need. Please reach out if that's the case.

**Comment by PrzemyslawTusinski** [comment]
In S3 there as there are couple of not correctly capitalized paths
```
    static final String SIZE = "supplementaryConfiguration.size.BucketSizeBytes";
    static final String NUMBER_OF_OBJECTS = "supplementaryConfiguration.size.NumberOfObjects";
    static final String ENCRYPTION = "supplementaryConfiguration.ServerSideEncryptionConfiguration.rules";
    static final String HOSTED = "supplementaryConfiguration.BucketWebsiteConfiguration";
    static final String REPLICATED = "supplementaryConfiguration.BucketReplicationConfiguration";
    static final String OBJECT_LOCK = "supplementaryConfiguration.BucketObjectLockConfiguration.objectLockEnabledAsString";
```

DynamoDB
`static final String BACKED_UP = "supplementaryConfiguration.ContinuousBackupsDescription.continuousBackupsStatus";`

In Reshift there is
` static final String CREATION_TIME = "resourceCreationTime";`
which should be 
` static final String CREATION_TIME = "createdIso";`
Unless there is something that translates createdIso to resourceCreationTime

All other paths are matching aws-magpie schema

Although in DynamicDB There is 
`static final String MOUNT_INFO = "configuration.mountTargets";`
Which matches both aws-magpie and aws-discovery. It should be 
`static final String MOUNT_INFO = "supplementaryConfiguration.mountTargets";`
